export const ADD_TACHE = 'ADD'
export const DELETE_TACHE = 'DELETE'
export const MODIF_TACHE = 'MODIF'
export const DELETE_ALL = 'DALL'
export const DELETE_TERMINE = 'DT'
export const DELETE_NOTERMINE = 'DNOT'